# Generated by Django 2.2.12 on 2021-12-08 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminKorisnici',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresa_ustanove', models.CharField(max_length=150)),
                ('naziv_admina', models.CharField(max_length=50)),
                ('kontakt_admina', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_eventa', models.CharField(max_length=100)),
                ('datum_odrzavanja', models.DateTimeField()),
                ('opis_eventa', models.CharField(max_length=500)),
                ('placanje_ulaza', models.BooleanField()),
                ('vrijeme_odrzavanja', models.DateTimeField()),
                ('cijena_ulaza', models.IntegerField()),
                ('zainteresirani', models.IntegerField()),
                ('dolaze', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mjesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postanski_broj', models.IntegerField()),
                ('naziv_mjesta', models.CharField(max_length=50)),
                ('mjesto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Objava',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov_objave', models.CharField(max_length=100)),
                ('vrijeme_objave', models.DateTimeField()),
                ('datum_objave', models.DateTimeField()),
                ('opis_objave', models.CharField(max_length=500)),
                ('autor_objave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.AdminKorisnici')),
            ],
        ),
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=1000)),
                ('eventi', models.ManyToManyField(to='main.Event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='mjesto_odrzavanja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Mjesto'),
        ),
        migrations.AddField(
            model_name='event',
            name='objava',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Objava'),
        ),
        migrations.AddField(
            model_name='adminkorisnici',
            name='mjesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Mjesto'),
        ),
    ]
