# Generated by Django 2.2.12 on 2021-12-08 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminkorisnici',
            name='mjesto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Mjesto'),
        ),
        migrations.AlterField(
            model_name='event',
            name='mjesto_odrzavanja',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Mjesto'),
        ),
        migrations.AlterField(
            model_name='event',
            name='objava',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Objava'),
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='eventi',
            field=models.ManyToManyField(blank=True, default=None, to='main.Event'),
        ),
        migrations.AlterField(
            model_name='objava',
            name='autor_objave',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.AdminKorisnici'),
        ),
    ]
