# Generated by Django 2.2.12 on 2021-12-08 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211208_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mjesto',
            old_name='mjesto',
            new_name='adresa',
        ),
        migrations.RemoveField(
            model_name='event',
            name='objava',
        ),
        migrations.AddField(
            model_name='objava',
            name='event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Event'),
        ),
    ]
