# Generated by Django 2.2.12 on 2021-12-08 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211208_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mjesto',
            old_name='adresa',
            new_name='drazava',
        ),
    ]
