# Generated by Django 3.1.4 on 2021-12-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211208_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminkorisnici',
            name='password',
            field=models.CharField(default=1234, max_length=1000),
            preserve_default=False,
        ),
    ]
