# Generated by Django 4.0 on 2022-01-26 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_adminkorisnici_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminkorisnici',
            name='kontakt_admina',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='cijena_ulaza',
            field=models.IntegerField(verbose_name=django.core.validators.MinValueValidator(0)),
        ),
        migrations.AlterField(
            model_name='event',
            name='dolaze',
            field=models.IntegerField(verbose_name=django.core.validators.MinValueValidator(0)),
        ),
        migrations.AlterField(
            model_name='event',
            name='zainteresirani',
            field=models.IntegerField(verbose_name=django.core.validators.MinValueValidator(0)),
        ),
        migrations.AlterField(
            model_name='mjesto',
            name='postanski_broj',
            field=models.IntegerField(verbose_name=django.core.validators.MinValueValidator(0)),
        ),
    ]
