# Generated by Django 4.0 on 2022-01-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_event_cijena_ulaza_alter_event_dolaze_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='datum_odrzavanja',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='vrijeme_odrzavanja',
            field=models.TimeField(),
        ),
    ]
