# Generated by Django 4.0.1 on 2022-02-05 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_alter_event_datum_odrzavanja_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korisnik',
            name='eventi',
        ),
        migrations.AddField(
            model_name='event',
            name='eventi',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
