# Generated by Django 4.0.1 on 2022-02-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_korisnik_eventi_event_eventi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eventi',
            new_name='korisnici',
        ),
    ]
