# Generated by Django 4.0.1 on 2022-02-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_eventi_event_korisnici'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Korisnik',
        ),
    ]
