# Generated by Django 3.2.8 on 2022-02-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='webstranica',
            field=models.CharField(default='', max_length=150),
        ),
    ]
