# Generated by Django 3.2.8 on 2022-02-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_profile_webstranica'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firma',
            field=models.CharField(default='', max_length=150),
        ),
    ]
